# Generated by Django 4.0 on 2022-03-23 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=128)),
                ('startTime', models.TimeField(default=datetime.datetime(2022, 3, 23, 2, 54, 35, 351198))),
                ('finsihTime', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'ToDo List',
            },
        ),
    ]
