# Generated by Django 4.0 on 2022-03-25 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2022, 3, 25, 0, 24, 6, 468230)),
        ),
    ]
